In [ ]:
#1.	Generate a tuple from the set ["aman", "222", 777, 400.4]

list1=["aman", "222", 777, 400.4]
tuple1=tuple(list1)
print(tuple1)
print(type(tuple1))

('aman', '222', 777, 400.4)
<class 'tuple'>


In [ ]:
#2.	Create a dictionary of your basic data: (a) Roll No (b) Last Name 
#(c) First Name (d) Date of birth. Print out the values and keys.


data={
    "rollNo" : "238",
    "lastName" : "Satya",
    "firstName" : "Mattaparti",
    "DOB" : "Sept 24"
}

print(data)
print('Value :',data.values())
print('Key :',data.keys())

{'rollNo': '238', 'lastName': 'Satya', 'firstName': 'Mattaparti', 'DOB': 'Sept 24'}
Value : dict_values(['238', 'Satya', 'Mattaparti', 'Sept 24'])
Key : dict_keys(['rollNo', 'lastName', 'firstName', 'DOB'])


In [ ]:
#3.	Use rand function to generate a 2-dimensional random array with seed.

import numpy as np
import random

random.seed(10)
array1=np.random.rand(2,2)
print("2-D array:",array1)


2-D array: [[0.23612945 0.54720754]
 [0.88164781 0.03276173]]


In [ ]:
#4.	Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)

import random

numb=random.uniform(0.0,1.0)
print("random:",numb)

import math 
num=-1234
print("absolute:",abs(num))



random: 0.4288890546751146
absolute: 1234


In [ ]:
#5.	Return a random integer N such that 20 <= N <= 90. 

import random 

num=random.randint(20,90)
print("random num:",num)

random num: 73


In [ ]:
# 6.	Given a population or set[11, 12, 13,14, 15]
# o	Return a 3 length list of unique elements without replacement.
# o	Shuffle the above set
# o	Print a random number from the set


set1=[11, 12, 13,14, 15]
print("3 length list:",random.sample(set1,3))


random.shuffle(set1)
print("Shuffled set:",set1)

num=random.choice(set1)
print("random number:",num)



3 length list: [15, 14, 12]
Shuffled set: [15, 14, 13, 12, 11]
random number: 15


In [1]:
#7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.


file=open("test.txt","w")
file.write("The King is Dead, Long Live The King")
file.close()
file=open("test.txt","r")
for i in file:
  print(i,end=" ")


The King is Dead, Long Live The King 

In [ ]:
#8.	Create an illustrative function to demonstrate use of:
# if, elif and else (b) for, while, break and continue.

def fun1(marks,top):
  sum=0
  for i in range(0,len(marks)):
    sum=sum+marks[i]
  
  avg=sum//len(marks)

  if avg>=90:
    print("A")
  elif avg>= 80 and avg<90:
    print("B")
  elif avg>= 70 and avg<80:
    print("C")
  elif avg<=50:
    print("F")
  else:
    print("P")
  
  i=0
  while(i<len(marks)):
    if marks[i]>=90:
      print(i+1,"excellent in math")
      
    elif marks[i]>= 80 and marks[i]<90:
      print(i+1,"good in math")

    else:
      print(i+1,"Can do better in math")
      break
    i+=1
  
  
mathmarks=[90,50,100]
top=3
fun1(mathmarks,top)


B
1 excellent in math
2 Can do better in math


In [ ]:
# 9.	Given a string "The King is Dead, Long Live The King" 
# o	Print the complete string
# o	Print first character of the string
# o	Print characters starting from 3rd to 5th
# o	Print string starting from 3rd character
# o	Split the words

string1="The King is Dead, Long Live The King"
print(string1)
print(string1[0])

print(string1[2:5])

print(string1[3:])

string=string1.split()
print(string)


The King is Dead, Long Live The King
T
e K
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [ ]:

# o	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements
#10.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).

import numpy as np
list1=[1,4,5,8]
arr=np.array(list1,float)
print("first and second elements:",arr[0:2])

arr1=[1,2,3]
arr2=[4,5,6]

arr3=np.array((arr1,arr2))
print("2-D array:",arr3)


first and second elements: [1. 4.]
2-D array: [[1 2 3]
 [4 5 6]]


In [ ]:
#11.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
# o	Slice and display the 2nd row.
# o	Write code to display as array([2., 5.]) 
# o	Find the length of the array


import numpy as np

arr=[[1,2,3],[4,5,6]]
arr1=np.array(arr,float)
print("second row:",arr1[1,:])
#print(arr1[(0,1),(1,1)])
print("array([2., 5.]):",arr1[:,1])
print("length of array",len(arr1))



second row: [4. 5. 6.]
array([2., 5.]): [2. 5.]
length of array 2


In [ ]:
#12.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first
# axis has five elements and whose second axis has two elements. Obtain the transpose of the array

import numpy as np
l1=[1,2,3,4,5,6,7,8,9,10]

arr=np.array(l1)
print("actual shape:",arr.shape)

narr=arr.reshape(2,5)
print("re-shaped:",narr.shape)
print("transpose:",narr.transpose())


actual shape: (10,)
re-shaped: (2, 5)
transpose: [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
#13.	Create an array from a list of 1,2 and 3.

import numpy as np

l1=[1,2,3]
arr=np.array(l1)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#14.	Fill an array [1,2,3] with a single value [9,9,9]. 
import numpy as np

l1=[1,2,3]
arr=np.array(l1)
arr[:]=9
print(arr)

[9 9 9]


In [ ]:
#15.	Sum the elements of array [2,4,5].
import numpy as np
l1=[2,4,5]
arr=np.array(l1)
print("sum:",np.sum(arr))

sum: 11


In [ ]:
#16.	Give the products of array [77,74,75]

import numpy as np

l1=[77,74,75]
arr=np.array(l1)

print("Product:",np.product(arr))


Product: 427350


In [ ]:
#17.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.


list1=[2,1,9,1,2,22,1,1,4,55,6,2,56]
arr=np.array([list1])

print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("variance",np.var(arr))
print("max",np.max(arr))
print("min",np.min(arr))
print("argmin",np.argmin(arr))
print("argmax",np.argmax(arr))
print("standard deviation",np.std(arr))


mean: 12.461538461538462
median: 2.0
variance 367.32544378698225
max 56
min 1
argmin 1
argmax 12
standard deviation 19.165736192147232


In [ ]:
#18.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
import numpy as np

l1=[1,1,4,5,5,5,7]

arr=np.array(l1)

print("unique:",np.unique(arr))
print("sorted:",np.sort(np.unique(arr)))




unique: [1 4 5 7]
sorted: [1 4 5 7]


In [ ]:
#19 Find dot product of two arrays [1, 2, 3]and [0, 1, 1]

import numpy as np
arr1=[1,2,3]
arr2=[0,1,1]

arr3=np.dot(arr1,arr2)
print("dotproduct:",arr3)

dotproduct: 5


In [ ]:
#20.	Find the eigenvalues and eigenvectors of matrix A.




In [ ]:
#21 . Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients

import numpy as np
arr=[[11, 22, 11, 31], [25, 33, 31, 28]]
arr1=np.array(arr,float)

print("correlation coefficient:",np.corrcoef(arr1))


correlation coefficient: [[1.         0.15997968]
 [0.15997968 1.        ]]
